### ISSUE TITLE
Custom endpoint parameters decorator example in documentation

### ISSUE THREAD

**Issue by raf66** [biga816/oak-decorators#6]
In the documentation, under the section "Custom endpoint parameters decorator", the JWT example provided (thank you) does not compile.  The error is reported against (handler) on registerCustomRouteParamDecorator.

```
Argument of type '(ctx: Context) => any' is not assignable to parameter of type 'ParamData | undefined'.
```

```js
export function JWT(propName?: string) {
    return function (targetClass: any, methodName: string, paramIndex: number) {
      
        const handler = (ctx: Context) =>
            propName ? ctx.state.jwtData?.[propName] : ctx.state.jwtData;

        registerCustomRouteParamDecorator(
            targetClass,
            methodName,
            paramIndex,
        )(handler);
    };
  }
```

**REQUEST**
Please add a custom endpoint parameters decorator example in the existing demo repository.

**Comment by biga816** [comment]
@raf66 Thank you for raising the issue!
It was a bug so I fixed it and published v0.1.5.

**Comment by raf66** [comment]
Thank you so much!   I really appreciate it.  Any chance you can publish to jsr.io?

**Comment by biga816** [comment]
Will do!

**Comment by biga816** [comment]
@raf66 I published this module to jsr.io!

**Comment by raf66** [comment]
You rock!  Thank you so much.
